// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmsghead.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cmsghead_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cmsghead_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cmsghead_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cmsghead_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cmsghead_2eproto;
namespace cmsg {
class CMsgHead;
class CMsgHeadDefaultTypeInternal;
extern CMsgHeadDefaultTypeInternal _CMsgHead_default_instance_;
}  // namespace cmsg
PROTOBUF_NAMESPACE_OPEN
template<> ::cmsg::CMsgHead* Arena::CreateMaybeMessage<::cmsg::CMsgHead>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cmsg {

// ===================================================================

class CMsgHead :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cmsg.CMsgHead) */ {
 public:
  CMsgHead();
  virtual ~CMsgHead();

  CMsgHead(const CMsgHead& from);
  CMsgHead(CMsgHead&& from) noexcept
    : CMsgHead() {
    *this = ::std::move(from);
  }

  inline CMsgHead& operator=(const CMsgHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgHead& operator=(CMsgHead&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CMsgHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CMsgHead* internal_default_instance() {
    return reinterpret_cast<const CMsgHead*>(
               &_CMsgHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CMsgHead& a, CMsgHead& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgHead* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CMsgHead* New() const final {
    return CreateMaybeMessage<CMsgHead>(nullptr);
  }

  CMsgHead* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CMsgHead>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CMsgHead& from);
  void MergeFrom(const CMsgHead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgHead* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cmsg.CMsgHead";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cmsghead_2eproto);
    return ::descriptor_table_cmsghead_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgStrFieldNumber = 2,
    kMsgSizeFieldNumber = 1,
    kMsgTypeFieldNumber = 3,
  };
  // string msg_str = 2;
  void clear_msg_str();
  const std::string& msg_str() const;
  void set_msg_str(const std::string& value);
  void set_msg_str(std::string&& value);
  void set_msg_str(const char* value);
  void set_msg_str(const char* value, size_t size);
  std::string* mutable_msg_str();
  std::string* release_msg_str();
  void set_allocated_msg_str(std::string* msg_str);
  private:
  const std::string& _internal_msg_str() const;
  void _internal_set_msg_str(const std::string& value);
  std::string* _internal_mutable_msg_str();
  public:

  // int32 msg_size = 1;
  void clear_msg_size();
  ::PROTOBUF_NAMESPACE_ID::int32 msg_size() const;
  void set_msg_size(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 msg_type = 3;
  void clear_msg_type();
  ::PROTOBUF_NAMESPACE_ID::int32 msg_type() const;
  void set_msg_type(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:cmsg.CMsgHead)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_str_;
  ::PROTOBUF_NAMESPACE_ID::int32 msg_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 msg_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cmsghead_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CMsgHead

// int32 msg_size = 1;
inline void CMsgHead::clear_msg_size() {
  msg_size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CMsgHead::msg_size() const {
  // @@protoc_insertion_point(field_get:cmsg.CMsgHead.msg_size)
  return msg_size_;
}
inline void CMsgHead::set_msg_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  msg_size_ = value;
  // @@protoc_insertion_point(field_set:cmsg.CMsgHead.msg_size)
}

// string msg_str = 2;
inline void CMsgHead::clear_msg_str() {
  msg_str_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CMsgHead::msg_str() const {
  // @@protoc_insertion_point(field_get:cmsg.CMsgHead.msg_str)
  return _internal_msg_str();
}
inline void CMsgHead::set_msg_str(const std::string& value) {
  _internal_set_msg_str(value);
  // @@protoc_insertion_point(field_set:cmsg.CMsgHead.msg_str)
}
inline std::string* CMsgHead::mutable_msg_str() {
  // @@protoc_insertion_point(field_mutable:cmsg.CMsgHead.msg_str)
  return _internal_mutable_msg_str();
}
inline const std::string& CMsgHead::_internal_msg_str() const {
  return msg_str_.GetNoArena();
}
inline void CMsgHead::_internal_set_msg_str(const std::string& value) {
  
  msg_str_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CMsgHead::set_msg_str(std::string&& value) {
  
  msg_str_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cmsg.CMsgHead.msg_str)
}
inline void CMsgHead::set_msg_str(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  msg_str_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cmsg.CMsgHead.msg_str)
}
inline void CMsgHead::set_msg_str(const char* value, size_t size) {
  
  msg_str_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cmsg.CMsgHead.msg_str)
}
inline std::string* CMsgHead::_internal_mutable_msg_str() {
  
  return msg_str_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CMsgHead::release_msg_str() {
  // @@protoc_insertion_point(field_release:cmsg.CMsgHead.msg_str)
  
  return msg_str_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgHead::set_allocated_msg_str(std::string* msg_str) {
  if (msg_str != nullptr) {
    
  } else {
    
  }
  msg_str_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg_str);
  // @@protoc_insertion_point(field_set_allocated:cmsg.CMsgHead.msg_str)
}

// int32 msg_type = 3;
inline void CMsgHead::clear_msg_type() {
  msg_type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CMsgHead::msg_type() const {
  // @@protoc_insertion_point(field_get:cmsg.CMsgHead.msg_type)
  return msg_type_;
}
inline void CMsgHead::set_msg_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  msg_type_ = value;
  // @@protoc_insertion_point(field_set:cmsg.CMsgHead.msg_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace cmsg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cmsghead_2eproto
